"""create_table_users

Revision ID: c789f5ab40fe
Revises: a1b2c3d4e5f6
Create Date: 2026-04-15 16:26:48.346480

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c789f5ab40fe"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = (
    "a1b2c3d4e5f6"  # pragma: allowlist secret
)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "gcuVersionAccepted", sa.Enum("V1", name="gcu_version_type"), nullable=False
        ),
        sa.Column("gcuAcceptedAt", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
