version: v1

agents:
  - id: "Rico"
    name: "Rico"
    type: "agent"
    class_path: "agentic_backend.agents.v1.production.rags.rag_expert.Rico"
    enabled: true
    chat_options:
      search_policy_selection: true
      libraries_selection: true
      search_rag_scoping: true
      deep_search_delegate: false
      attach_files: true
      include_corpus_in_search: true

  # - id: "Archie"
  #   name: "Archie"
  #   type: "agent"
  #   class_path: "agentic_backend.agents.v1.production.rags.archie.Archie"
  #   enabled: true
  #   chat_model: {}
  #   chat_options:
  #     search_policy_selection: true
  #     libraries_selection: true
  #     search_rag_scoping: true
  #     attach_files: true

  - id: "Tessa"
    name: "Tessa"
    type: "agent"
    class_path: "agentic_backend.agents.v1.production.tabular.tabular_expert.Tessa"
    enabled: true

  - id: "Spot"
    name: "Spot"
    type: "agent"
    class_path: "agentic_backend.agents.v1.production.prometheus.prometheus_expert.Spot"
    enabled: true

  # - id: "SlideMaker"
  #   name: "SlideMaker"
  #   type: "agent"
  #   definition_ref: "v2.sample.slide_maker"

  - id: "SQL Agent"
    name: "SQL Agent"
    type: "agent"
    definition_ref: "v2.production.sql_analyst"

  - id: "Corpus Investigator Deep"
    name: "Corpus Investigator Deep"
    type: "agent"
    definition_ref: "v2.deep.corpus_investigator"

  - id: "DVARiskValidatorGraph"
    name: "DVA Risk Validator"
    type: "agent"
    definition_ref: "v2.production.dva_risk_validator.graph"

  - id: "DVARiskValidatorQA"
    name: "DVA Risk Validator QA"
    type: "agent"
    definition_ref: "v2.production.dva_risk_validator.qa"

  - id: "BankTransfer"
    name: "Bank Transfer"
    type: "agent"
    definition_ref: "v2.sample.bank_transfer"

react_profiles:
  - profile_id: "custodian"
    enabled: true
  - profile_id: "rag_expert"
    enabled: true
  - profile_id: "sentinel"
    enabled: true
