version: v1

agents:
  - id: "Georges"
    name: "Georges"
    type: "agent"
    class_path: "agentic_backend.agents.generalist.generalist_expert.Georges"
    enabled: true
    chat_options:
      attach_files: false

  - id: "Rico"
    name: "Rico"
    type: "agent"
    class_path: "agentic_backend.agents.rags.rag_expert.Rico"
    enabled: true
    chat_options:
      search_policy_selection: true
      libraries_selection: true
      search_rag_scoping: true
      deep_search_delegate: false
      attach_files: true
      include_corpus_in_search: true

  - id: "Rico Senior"
    name: "Rico Senior"
    type: "agent"
    class_path: "agentic_backend.agents.rags.advanced_rag_expert.AdvancedRico"
    enabled: true
    chat_options:
      search_policy_selection: true
      libraries_selection: true
      search_rag_scoping: true
      deep_search_delegate: false
      attach_files: true

  - id: "Aegis"
    name: "Aegis"
    type: "agent"
    class_path: "agentic_backend.agents.aegis.aegis_rag_expert.Aegis"
    enabled: true

  - id: "Archie"
    name: "Archie"
    type: "agent"
    class_path: "agentic_backend.agents.rags.archie.Archie"
    enabled: true
    chat_model: {}
    chat_options:
      search_policy_selection: true
      libraries_selection: true
      search_rag_scoping: true
      attach_files: true

  - id: "Tessa"
    name: "Tessa"
    type: "agent"
    class_path: "agentic_backend.agents.tabular.tabular_expert.Tessa"
    enabled: true
