# Copyright Thales 2026
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Production definition for the Basic ReAct agent family.

What is "Basic ReAct"?
    It is a flexible, profile-driven assistant. Instead of writing a new
    Agent class for every bot (e.g. HR Bot, IT Bot), we use this single class
    and configure it with a "Profile".

How to add a new bot:
    1. Do NOT edit this file.
    2. Create a new file in `profiles/` (e.g. `profiles/it_support.py`).
    3. Define a `ReActProfile` there.
"""

from __future__ import annotations

from typing import Any

from pydantic import Field, model_validator

from agentic_backend.core.agents.agent_spec import FieldSpec, UIHints
from agentic_backend.core.agents.v2 import (
    GuardrailDefinition,
    ReActAgentDefinition,
    ReActPolicy,
    ToolApprovalPolicy,
    ToolRefRequirement,
)

from .profile_registry import (
    get_react_profile,
    list_react_profiles,
    profile_options_summary,
)


def _default_react_profile_id() -> str:
    profiles = list_react_profiles()
    if not profiles:
        raise ValueError(
            "No Basic ReAct profiles are available. "
            "Define at least one profile module under basic_react/profiles."
        )
    for preferred_id in ("base_assistant",):
        for profile in profiles:
            if profile.profile_id == preferred_id:
                return profile.profile_id
    return profiles[0].profile_id


DEFAULT_REACT_PROFILE_ID = _default_react_profile_id()


def _basic_react_fields() -> tuple[FieldSpec, ...]:
    """
    Build the author/admin-facing field surface for the generic ReAct agent.

    Why this helper exists:
    - the available profile ids come from the backend profile library
    - the field list should remain a single clear declaration in this file
    - the generic agent stays simple, while profiles provide stronger defaults
    """

    return (
        FieldSpec(
            key="react_profile_id",
            type="select",
            title="Starting profile",
            description=(
                "Choose a backend-defined starting profile. "
                "A profile can prefill the prompt, MCP defaults, and safety policy.\n"
                f"{profile_options_summary()}"
            ),
            required=True,
            default=DEFAULT_REACT_PROFILE_ID,
            enum=[profile.profile_id for profile in list_react_profiles()],
            ui=UIHints(group="Profile", hide=True),
        ),
        FieldSpec(
            key="system_prompt_template",
            type="prompt",
            title="agentTuning.fields.prompts_system.title",
            description="agentTuning.fields.prompts_system.description",
            required=True,
            ui=UIHints(
                group="agentTuning.groups.prompts", multiline=True, markdown=True
            ),
        ),
        FieldSpec(
            key="enable_tool_approval",
            type="boolean",
            title="Require approval for mutating tools",
            description=(
                "When enabled, the runtime pauses before tool calls that look "
                "like state-changing actions."
            ),
            required=False,
            default=False,
            ui=UIHints(group="Safety", hide=True),
        ),
        FieldSpec(
            key="approval_required_tools",
            type="array",
            item_type="string",
            title="Always-approve tool names",
            description=(
                "Exact tool names that must always ask for human approval "
                "before execution."
            ),
            required=False,
            default=[],
            ui=UIHints(group="Safety", hide=True),
        ),
    )


class BasicReActDefinition(ReActAgentDefinition):
    """
    Baseline definition for generic ReAct assistants.

    Quick edit guide:
    - `system_prompt_template`: assistant behavior
    - `declared_tool_refs`: exact Fred tools this agent may use
    - `fields`: what admins can tune in UI
    - `policy()`: small runtime behavior switches
    """

    agent_id: str = "basic.react.v2"
    role: str = "General assistant with optional tools"
    description: str = (
        "A concise assistant that can answer directly or use explicitly declared "
        "platform tools when they are available."
    )
    tags: tuple[str, ...] = ("assistant", "react")
    # Author/admin-owned: choose the business starting profile.
    # This does not create a new runtime. It selects a backend-defined recipe
    # that can prefill prompt, MCP defaults, and safety policy.
    react_profile_id: str = DEFAULT_REACT_PROFILE_ID
    # Author-owned: business instructions only.
    # Main business instruction for the agent.
    # A developer edits this when they want to change the answer style or core
    # user-facing behavior.
    system_prompt_template: str | None = Field(
        default=None,
        min_length=1,
    )
    # Author-owned: optional human approval for sensitive tool calls.
    # A developer enables this when a generic tool agent should pause before
    # executing mutating actions such as create/update/delete/notify.
    enable_tool_approval: bool = False
    # Author-owned: exact tool names that must always require approval.
    # This lets a developer protect specific business actions even when their
    # name does not match the default mutating-tool heuristics.
    approval_required_tools: tuple[str, ...] = ()
    # Author-owned: explicit operating constraints appended by the runtime.
    # Profiles can set these to enforce grounding/uncertainty style rules.
    guardrails: tuple[GuardrailDefinition, ...] = ()
    # Author-owned: UI tuning surface exposed for this agent.
    # UI-exposed configuration for this agent.
    # A developer adds fields here when users should be able to tune prompts or
    # other business options from the interface.
    fields: tuple[FieldSpec, ...] = _basic_react_fields()
    # Author-owned: declare exact tools the agent expects in its contract.
    # This is for authoring/inspection/validation, not LangChain wiring.
    # This basic example starts without tools, but a developer can add them
    # later by listing tool refs here.
    declared_tool_refs: tuple[ToolRefRequirement, ...] = ()

    @model_validator(mode="before")
    @classmethod
    def _apply_profile_defaults(cls, data: Any) -> Any:
        """
        Populate profile-owned fields from the selected profile when the caller
        did not provide them explicitly.

        This makes BasicReActDefinition(react_profile_id="rag_expert") produce
        the same result as the legacy bridge — tools, guardrails, prompt, and
        approval policy are all filled in from the profile automatically.

        Only fields absent from the constructor call are filled. Explicit values
        always win.
        """
        if not isinstance(data, dict):
            return data
        profile_id = data.get("react_profile_id")
        if not profile_id or not isinstance(profile_id, str):
            return data
        try:
            profile = get_react_profile(profile_id.strip())
        except ValueError:
            return data
        for field, value in (
            ("system_prompt_template", profile.system_prompt_template),
            ("declared_tool_refs", profile.declared_tool_refs),
            ("default_mcp_servers", profile.mcp_servers),
            ("guardrails", profile.guardrails),
            ("enable_tool_approval", profile.enable_tool_approval),
            ("approval_required_tools", profile.approval_required_tools),
        ):
            if field not in data:
                data[field] = value
        return data

    def policy(self) -> ReActPolicy:
        """
        Return the runtime policy used by `ReActRuntime`.
        """

        # Author-owned: declare behavior. Framework-owned: execute it.
        return ReActPolicy(
            system_prompt_template=self.system_prompt_template,
            tool_approval=ToolApprovalPolicy(
                enabled=self.enable_tool_approval,
                always_require_tools=tuple(self.approval_required_tools),
            ),
            guardrails=self.guardrails,
        )
