# Copyright Thales 2026
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Runtime primitives used by all v2 agents.

Read this file when you need to understand three things quickly:
1. Which events the runtime can emit (`RuntimeEvent*`).
2. Which platform capabilities a runtime can use (`RuntimeServices` ports).
3. What lifecycle a runtime implementation must follow (`AgentRuntime`).

If you are authoring an agent, you usually do not edit this file. You edit a
definition (`ReActAgentDefinition` or `GraphAgentDefinition`) and let runtime
implementations execute it.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import AsyncIterator, Sequence
from dataclasses import dataclass
from enum import Enum
from typing import Annotated, Any, Generic, List, Literal, Protocol, TypeAlias, TypeVar

from fred_core.portable import MetricsProvider, Span, Tracer
from fred_core.store import VectorSearchHit
from pydantic import BaseModel, ConfigDict, Field

from .context import (
    AgentInvocationRequest,
    AgentInvocationResult,
    BoundRuntimeContext,
    ConversationTurn,
    FsEntry,
    JsonScalar,
    PublishedArtifact,
    ToolInvocationRequest,
    ToolInvocationResult,
    UiPart,
)
from .models import AgentDefinition

ChatModelHandle: TypeAlias = object
RuntimeToolHandle: TypeAlias = object
CheckpointHandle: TypeAlias = object
SpanPort: TypeAlias = Span
TracerPort: TypeAlias = Tracer


class FrozenModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, arbitrary_types_allowed=True)


class CheckpointStrategy(str, Enum):
    SESSION = "session"
    EXCHANGE = "exchange"
    DISABLED = "disabled"


class RuntimeEventKind(str, Enum):
    STATUS = "status"
    TOOL_CALL = "tool_call"
    TOOL_RESULT = "tool_result"
    THOUGHT_START = "thought_start"
    THOUGHT_DELTA = "thought_delta"
    THOUGHT_END = "thought_end"
    AWAITING_HUMAN = "awaiting_human"
    ASSISTANT_DELTA = "assistant_delta"
    NODE_ERROR = "node_error"
    FINAL = "final"
    TURN_PERSISTED = "turn_persisted"
    EXECUTION_ERROR = "execution_error"


class ExecutionConfig(FrozenModel):
    """
    Per-run execution options resolved by the chat/session layer.

    Practical meaning:
    - `session_id` / `checkpoint_id`: resume the right conversation state.
      session_id is the single public-facing conversation identity. Internally
      it is passed as LangGraph's `thread_id` — that mapping is an
      implementation detail and must not leak into any public API or CLI.
    - `adapter_config`: optional adapter-specific config passthrough when one runtime
      bridge needs extra execution metadata.
    - `max_steps`: hard stop against runaway loops.
    - `resume_payload`: data provided by a previous HITL pause.
    """

    checkpoint_strategy: CheckpointStrategy = CheckpointStrategy.SESSION
    session_id: str | None = None
    checkpoint_id: str | None = None
    adapter_config: dict[str, object] = Field(default_factory=dict)
    max_steps: int = Field(default=100, ge=1)
    stream_intermediate_events: bool = True
    resume_payload: object | None = None
    invocation_turns: tuple[ConversationTurn, ...] = ()
    """Prior conversation turns forwarded by the calling agent for context seeding."""


class RuntimeEventBase(FrozenModel):
    sequence: int = Field(default=0, ge=0)


# Phase discriminator for THOUGHT_START/DELTA/END events.
# Authors pass this to context.thinking() or emit_thought() to label the
# reasoning phase. The frontend uses it to render distinct visual treatments.
ThoughtKind = Literal[
    "planning",  # agent deciding what to do / which tools to call
    "tool_use",  # reasoning immediately before or after a tool invocation
    "observation",  # interpreting a tool result
    "reflection",  # self-correction or re-planning after an observation
    "synthesis",  # assembling the final answer from collected evidence
]


class StatusRuntimeEvent(RuntimeEventBase):
    """Generic operational progress signal. No chain-of-thought semantics."""

    kind: Literal[RuntimeEventKind.STATUS] = RuntimeEventKind.STATUS
    status: str = Field(..., min_length=1)
    detail: str | None = None


class ThoughtStartEvent(RuntimeEventBase):
    """Opens a reasoning block. Paired with THOUGHT_DELTA(s) and THOUGHT_END."""

    kind: Literal[RuntimeEventKind.THOUGHT_START] = RuntimeEventKind.THOUGHT_START
    thought_id: str = Field(..., min_length=1)
    phase: ThoughtKind
    title: str | None = None
    source: Literal["authored", "model_native"] = "authored"


class ThoughtDeltaEvent(RuntimeEventBase):
    """One incremental text fragment streamed into an open reasoning block."""

    kind: Literal[RuntimeEventKind.THOUGHT_DELTA] = RuntimeEventKind.THOUGHT_DELTA
    thought_id: str = Field(..., min_length=1)
    delta: str = Field(..., min_length=1)


class ThoughtEndEvent(RuntimeEventBase):
    """Closes a reasoning block. Always emitted even if the block body raised."""

    kind: Literal[RuntimeEventKind.THOUGHT_END] = RuntimeEventKind.THOUGHT_END
    thought_id: str = Field(..., min_length=1)
    conclusion: str | None = None
    duration_ms: int | None = None


class ThoughtRecord(FrozenModel):
    """
    Durable record of one completed reasoning block, assembled by the runtime.

    Accumulated into GraphExecutionOutput.thought_trace for evaluation harnesses
    and session history replay. Not streamed — derived from THOUGHT_* events.
    """

    thought_id: str
    phase: ThoughtKind
    title: str | None = None
    text: str = ""
    conclusion: str | None = None
    duration_ms: int | None = None
    source: Literal["authored", "model_native"] = "authored"


class ToolCallRuntimeEvent(RuntimeEventBase):
    kind: Literal[RuntimeEventKind.TOOL_CALL] = RuntimeEventKind.TOOL_CALL
    tool_name: str = Field(..., min_length=1)
    call_id: str = Field(..., min_length=1)
    arguments: dict[str, object] = Field(default_factory=dict)


class ToolResultRuntimeEvent(RuntimeEventBase):
    kind: Literal[RuntimeEventKind.TOOL_RESULT] = RuntimeEventKind.TOOL_RESULT
    call_id: str = Field(..., min_length=1)
    content: str = Field(default="")
    tool_name: str | None = None
    is_error: bool = False
    sources: tuple[VectorSearchHit, ...] = ()
    ui_parts: tuple[UiPart, ...] = ()


class HumanChoiceOption(FrozenModel):
    id: str = Field(..., min_length=1)
    label: str = Field(..., min_length=1)
    description: str | None = None
    default: bool = False


class HumanInputRequest(FrozenModel):
    """
    Structured question shown to the user when runtime needs input.

    Use this model to represent business questions (choice, free text, or
    both). The UI renders this object directly.
    """

    stage: str | None = None
    title: str | None = None
    question: str | None = None
    choices: tuple[HumanChoiceOption, ...] = ()
    free_text: bool = False
    metadata: dict[str, JsonScalar] = Field(default_factory=dict)
    checkpoint_id: str | None = None


class AwaitingHumanRuntimeEvent(RuntimeEventBase):
    kind: Literal[RuntimeEventKind.AWAITING_HUMAN] = RuntimeEventKind.AWAITING_HUMAN
    request: HumanInputRequest


class AssistantDeltaRuntimeEvent(RuntimeEventBase):
    kind: Literal[RuntimeEventKind.ASSISTANT_DELTA] = RuntimeEventKind.ASSISTANT_DELTA
    delta: str = Field(..., min_length=1)


class NodeErrorRuntimeEvent(RuntimeEventBase):
    """
    Emitted when a node handler raises an unhandled exception and the node
    declares `on_error` routing.

    Why this exists:
    - infrastructure failures (MCP server down, network timeout) must be
      distinguishable from normal agent answers at the UI layer
    - the UI can show an inline warning banner instead of displaying the error
      string as if it were a regular answer

    Fields:
    - `node_id`: the node that raised
    - `error_message`: str(exc) — a short technical description
    - `routed_to`: the node the runtime is routing to next (the on_error target)
    """

    kind: Literal[RuntimeEventKind.NODE_ERROR] = RuntimeEventKind.NODE_ERROR
    node_id: str = Field(..., min_length=1)
    error_message: str = Field(..., min_length=1)
    routed_to: str = Field(..., min_length=1)


class FinalRuntimeEvent(RuntimeEventBase):
    kind: Literal[RuntimeEventKind.FINAL] = RuntimeEventKind.FINAL
    content: str = Field(default="")
    sources: tuple[VectorSearchHit, ...] = ()
    ui_parts: tuple[UiPart, ...] = ()
    model_name: str | None = None
    token_usage: dict[str, int] | None = None
    finish_reason: str | None = None


class TurnPersistedEvent(RuntimeEventBase):
    """
    Signals that a completed turn's history has been durably persisted.

    Current SSE delivery status: NOT emitted live over the SSE stream.
    History is written fire-and-forget after the stream closes, so this event
    cannot be reliably delivered before connection close. `final` is the only
    reliable end-of-turn signal for SSE clients.

    This type is kept in the contract for future use (e.g. a separate push
    channel or an explicit wiring decision in a later phase).

    Architectural note:
    - fred-runtime is a CONSUMER of checkpoint/history storage, not its
      ownership authority.
    - exchange_id links the persisted turn to the runtime event sequence.
    """

    kind: Literal[RuntimeEventKind.TURN_PERSISTED] = RuntimeEventKind.TURN_PERSISTED
    session_id: str = Field(..., min_length=1)
    exchange_id: str | None = None


class RuntimeErrorEvent(RuntimeEventBase):
    """
    Emitted when the agent execution pipeline raises an unhandled exception.

    Why this exists:
    - Before this type, the exception handler yielded {"error": str(exc)} with
      no `kind` field — invisible to any SSE client dispatching on `kind`.
    - Promoting it to a typed event allows the frontend to surface agent crashes
      with the same dispatch path as other runtime events.

    SSE client guidance:
    - Treat `execution_error` as a terminal event: no `final` will follow.
    - Display `message` as a technical error detail (not as assistant content).
    - The stream closes after this event is delivered.
    """

    kind: Literal[RuntimeEventKind.EXECUTION_ERROR] = RuntimeEventKind.EXECUTION_ERROR
    message: str = Field(..., min_length=1)


RuntimeEvent: TypeAlias = Annotated[
    StatusRuntimeEvent
    | ThoughtStartEvent
    | ThoughtDeltaEvent
    | ThoughtEndEvent
    | ToolCallRuntimeEvent
    | ToolResultRuntimeEvent
    | AwaitingHumanRuntimeEvent
    | AssistantDeltaRuntimeEvent
    | NodeErrorRuntimeEvent
    | FinalRuntimeEvent
    | TurnPersistedEvent
    | RuntimeErrorEvent,
    Field(discriminator="kind"),
]


class TokenProviderPort(ABC):
    @abstractmethod
    def get_bearer_token(self, binding: BoundRuntimeContext) -> str:
        """Return a bearer token appropriate for the currently bound runtime."""


class ChatModelFactoryPort(ABC):
    @abstractmethod
    def build(
        self, definition: AgentDefinition, binding: BoundRuntimeContext
    ) -> ChatModelHandle:
        """
        Resolve the canonical chat model for the currently bound agent runtime.

        This port exists so v2 runtimes stay platform-owned and testable:
        agent definitions remain pure declarations, while model selection stays
        an injected capability that Fred can later align with a broader SDK.
        """

    def build_for_operation(
        self,
        *,
        definition: AgentDefinition,
        binding: BoundRuntimeContext,
        purpose: str,
        operation: str | None,
    ) -> ChatModelHandle | None:
        """
        Optionally resolve a chat model for a specific operation within one turn.

        Why this exists:
        - advanced routing factories (e.g. RoutedChatModelFactory) can select
          different models for different phases of a ReAct/Graph turn (e.g.
          "routing" vs "planning" vs "answering")
        - base implementations return None to signal "use build() instead"

        How to use it:
        - runtimes call this first; fall back to build() when None is returned
        - do not override if the factory does not support per-operation routing
        """
        return None


class ToolInvokerPort(ABC):
    @abstractmethod
    async def invoke(self, request: ToolInvocationRequest) -> ToolInvocationResult:
        """Invoke a tool through the platform's transport layer."""


class AgentInvokerPort(ABC):
    """
    Platform port for invoking a registered fred v2 agent from a graph node.

    Why this port exists:
    - graph nodes should be able to call other agents without knowing whether
      the target runs in-process, as a Temporal child workflow, or over HTTP
    - this port is the single extension point; concrete implementations are
      injected by the runtime, not the agent author

    How to implement it:
    - provide one concrete subclass per deployment strategy
      (e.g. ``TemporalAgentInvoker``, ``LocalAgentInvoker``)
    - the implementation is responsible for agent lookup, execution, and
      mapping the agent's output to ``AgentInvocationResult``

    How to use it:
    - do not call this port directly from agent code; use
      ``GraphNodeContext.invoke_agent`` instead
    """

    @abstractmethod
    async def invoke(self, request: AgentInvocationRequest) -> AgentInvocationResult:
        """
        Run a registered agent for one turn and return its output.

        The implementation decides the execution strategy (in-process, child
        workflow, remote call). It must populate ``AgentInvocationResult`` with
        at least ``content`` and ``is_error``.
        """


class ToolProviderPort(ABC):
    @abstractmethod
    def bind(self, binding: BoundRuntimeContext) -> None:
        """Refresh context-scoped tool-provider state for the current runtime."""

    @abstractmethod
    async def activate(self) -> None:
        """Initialize any heavy provider resources before tool execution."""

    @abstractmethod
    def get_tools(self) -> tuple[RuntimeToolHandle, ...]:
        """Return the current runtime-provided tool set."""

    @abstractmethod
    async def aclose(self) -> None:
        """Release provider resources."""


class WorkspaceFileNotFound(Exception):
    """Raised by ``WorkspaceFsPort`` when a path does not exist."""


class WorkspaceFsPort(ABC):
    """
    Path-addressed access to the team-rooted virtual filesystem (FILES-04).

    Why this port exists:
    - agents read and write files by short, author-relative paths; the team and the acting
      user are injected from the verified session context, never typed by the agent
    - this is the single file capability behind ``ctx.read/write/ls/resolve_template``

    Path grammar (implemented by the concrete adapter, not the agent):
    - a bare/relative path → the acting user's private space
    - a leading ``shared/`` → the team-shared space
    - an absolute ``/teams/{t}/...`` is accepted only when ``t`` is the session team

    Implementations must raise ``WorkspaceFileNotFound`` for a missing path so callers such
    as ``resolve_template`` can fall through to the next candidate.
    """

    @abstractmethod
    def bind(self, binding: BoundRuntimeContext) -> None:
        """Refresh context-scoped filesystem state for the current runtime."""

    @abstractmethod
    async def read_bytes(self, path: str) -> bytes:
        """Read one file as raw bytes."""

    @abstractmethod
    async def read_text(self, path: str) -> str:
        """Read one file as UTF-8 text."""

    @abstractmethod
    async def read_user_bytes(self, path: str) -> bytes:
        """Read one file from the user's Mon espace (``teams/{team}/users/{uid}/...``).

        For the run's acting user only; raise ``WorkspaceFileNotFound`` if missing.
        """

    @abstractmethod
    async def read_team_bytes(self, path: str) -> bytes:
        """Read one file from the team's Espace d'equipe (``teams/{team}/shared/...``).

        Governed by the user's team read access; raise ``WorkspaceFileNotFound`` if missing.
        """

    @abstractmethod
    async def write(
        self,
        path: str,
        content: bytes,
        *,
        content_type: str | None = None,
        title: str | None = None,
    ) -> PublishedArtifact:
        """Write one file and return its downloadable description."""

    @abstractmethod
    async def ls(self, path: str = "") -> list[FsEntry]:
        """List one directory."""

    @abstractmethod
    async def delete(self, path: str) -> None:
        """Delete one file."""

    @abstractmethod
    async def link_for(self, path: str) -> PublishedArtifact:
        """
        Return a downloadable description of an **existing** file — no copy.

        Used to hand a file already in the workspace back to the user as a download link
        (RFC §7.3). The adapter mints a signed, short-TTL URL; raise
        ``WorkspaceFileNotFound`` if the path does not exist.
        """


class HistoryStorePort(Protocol):
    """
    Port for writing and reading conversation history from a durable store.

    Why this port exists:
    - ``fred-sdk`` must not import from ``fred-core`` (layer rule), so this
      protocol defines the interface using loose ``Any`` types for messages
    - the concrete implementation (``fred_core.history.PostgresHistoryStore``)
      is injected at runtime by ``fred-runtime``; the sdk-level runtime never
      needs to know the message type

    How to implement it:
    - provide ``fred_core.history.PostgresHistoryStore`` as the concrete impl
    - inject via ``RuntimeServices.history_store``
    - the concrete type for ``messages`` is ``list[ChatMessage]`` at call sites

    How to use it:
    - runtimes or adapters that write history call ``save`` once per turn
    - ``get`` is called by pod endpoints to reconstruct the message timeline
    - ``list_sessions`` is called by the session-listing endpoint
    """

    async def save(
        self,
        session_id: str,
        messages: List[Any],
        user_id: str,
        team_id: str | None = None,
        agent_instance_id: str | None = None,
    ) -> None:
        """Persist a batch of messages for one turn."""
        ...

    async def get(
        self,
        session_id: str,
        user_id: str | None = None,
    ) -> List[Any]:
        """Retrieve messages for a session.

        When user_id is provided, only rows belonging to that user are returned.
        Returns [] when the session exists but no rows match — callers cannot
        distinguish "wrong owner" from "empty session" by design.
        """
        ...

    async def list_sessions(
        self,
        user_id: str,
    ) -> List[str]:
        """Return distinct session IDs for a user, most recent first."""
        ...

    async def delete_session(
        self,
        session_id: str,
        user_id: str | None = None,
    ) -> int:
        """Permanently remove history rows for a session.

        When user_id is provided, only rows belonging to that user are deleted.
        Returns the number of rows removed (0 when session not found or not owned).
        """
        ...

    async def session_belongs_to_user(
        self,
        session_id: str,
        user_id: str,
    ) -> bool:
        """Return True iff at least one history row exists for (session_id, user_id)."""
        ...

    async def next_rank(self, session_id: str) -> int:
        """Return the next available rank for a session (MAX(rank) + 1, or 0 if empty)."""
        ...


class DocumentSearchResult(FrozenModel):
    """
    Typed result of one capability-scoped document vector search (CAPAB-01 #1906).

    Wraps the ranked `VectorSearchHit`s so a capability can feed the hit JSON to
    the model AND ride the typed hits on its tool artifact's `sources` for the
    chat Sources panel — without depending on any fred-runtime client type.
    """

    hits: tuple[VectorSearchHit, ...] = ()


class DocumentSearchPort(ABC):
    """
    Capability-safe vector search over the platform document corpus (CAPAB-01 #1906).

    Doctrine (RFC AGENT-CAPABILITY §3.8, §10): a capability reaches platform
    services ONLY through typed optional ports on `RuntimeServices`. This port
    takes SCOPE PARAMETERS (library tags, document uids, policy) and NEVER a
    caller-supplied context, identity, or access token — auth and identity come
    solely from the adapter's privately-captured per-turn binding, which never
    enters `CapabilityContext`.

    Scoping precedence the pilot enforces across the two seams
    (`turn_option ⊆ capability_config ⊆ session_binding`):
    - the capability narrows its stored-config scope by the turn's option slice
      and passes the result as these parameters (enforces
      `turn_option ⊆ capability_config`);
    - the adapter intersects those parameters with the session binding's own
      scope before calling Knowledge Flow (enforces `⊆ session_binding`).
    """

    @abstractmethod
    async def search(
        self,
        query: str,
        *,
        top_k: int = 8,
        library_tag_ids: Sequence[str] | None = None,
        document_uids: Sequence[str] | None = None,
        search_policy: str | None = None,
    ) -> DocumentSearchResult:
        """
        Run one scoped vector search and return typed hits.

        `library_tag_ids` / `document_uids` are the capability's already-narrowed
        scope (None = "no capability-side narrowing at this level"); the adapter
        further bounds them by the session binding. `search_policy` overrides the
        binding's default policy when provided.
        """


@dataclass(frozen=True, slots=True)
class RuntimeServices:
    """
    Dependencies injected into a runtime instance.

    Think of this as the runtime toolbox:
    - model factory
    - tool invocation/provider
    - artifact publish/read
    - tracing and KPI
    - checkpointer
    - history store (durable conversation history, independent from the checkpointer)

    In production, most debugging starts by checking which services were
    actually injected for a given runtime.
    """

    tracer: TracerPort | None = None
    chat_model_factory: ChatModelFactoryPort | None = None
    token_provider: TokenProviderPort | None = None
    tool_invoker: ToolInvokerPort | None = None
    tool_provider: ToolProviderPort | None = None
    agent_invoker: AgentInvokerPort | None = None
    workspace_fs: WorkspaceFsPort | None = None
    metrics: MetricsProvider | None = None
    checkpointer: CheckpointHandle | None = None
    history_store: HistoryStorePort | None = None
    # Capability-safe scoped vector search over the document corpus (CAPAB-01
    # #1906). Optional and additive: the `DocumentAccessCapability` reads it via
    # `ctx.services.document_search`; the port takes scope parameters only — the
    # per-turn binding and raw access token stay private to the adapter.
    document_search: DocumentSearchPort | None = None


InputModelT = TypeVar("InputModelT", bound=BaseModel)
OutputModelT = TypeVar("OutputModelT", bound=BaseModel)
DefinitionT = TypeVar("DefinitionT", bound=AgentDefinition)


class Executor(ABC, Generic[InputModelT, OutputModelT]):
    @abstractmethod
    async def invoke(
        self, input_model: InputModelT, config: ExecutionConfig
    ) -> OutputModelT:
        """Execute the agent once and return the final output."""

    @abstractmethod
    def stream(
        self, input_model: InputModelT, config: ExecutionConfig
    ) -> AsyncIterator[RuntimeEvent]:
        """Execute the agent and yield runtime events."""


class AgentRuntime(ABC, Generic[DefinitionT, InputModelT, OutputModelT]):
    """
    Base lifecycle shared by concrete runtimes (ReAct/Graph).

    Lifecycle to remember:
    - `bind(...)`: cheap context switch (session/user/token).
    - `activate()`: one-time heavy initialization.
    - `get_executor()`: returns the executable engine.

    If a runtime behaves oddly across sessions, inspect `bind()`/`on_bind()`
    first; if it leaks resources, inspect `dispose()`/`on_dispose()`.
    """

    def __init__(self, *, definition: DefinitionT, services: RuntimeServices):
        self._definition = definition
        self._services = services
        self._binding: BoundRuntimeContext | None = None
        self._activated = False
        self._disposed = False
        self._executor: Executor[InputModelT, OutputModelT] | None = None

    @property
    def definition(self) -> DefinitionT:
        return self._definition

    @property
    def services(self) -> RuntimeServices:
        return self._services

    @property
    def binding(self) -> BoundRuntimeContext:
        if self._binding is None:
            raise RuntimeError("AgentRuntime is not bound. Call bind() first.")
        return self._binding

    @property
    def is_activated(self) -> bool:
        return self._activated

    @property
    def is_disposed(self) -> bool:
        return self._disposed

    def bind(self, binding: BoundRuntimeContext) -> None:
        if self._disposed:
            raise RuntimeError("Cannot bind a disposed AgentRuntime.")

        self._binding = binding
        self._executor = None
        self.on_bind(binding)

    def on_bind(self, binding: BoundRuntimeContext) -> None:
        """Optional hook for subclasses to rebuild context-scoped helper state."""

    async def activate(self) -> None:
        if self._disposed:
            raise RuntimeError("Cannot activate a disposed AgentRuntime.")
        if self._activated:
            return
        binding = self.binding
        await self.on_activate(binding)
        self._activated = True

    async def on_activate(self, binding: BoundRuntimeContext) -> None:
        """Optional hook for one-time heavy activation logic."""

    async def get_executor(self) -> Executor[InputModelT, OutputModelT]:
        if self._disposed:
            raise RuntimeError("Cannot build an executor from a disposed AgentRuntime.")

        await self.activate()
        binding = self.binding
        if self._executor is None:
            self._executor = await self.build_executor(binding)
        return self._executor

    @abstractmethod
    async def build_executor(
        self, binding: BoundRuntimeContext
    ) -> Executor[InputModelT, OutputModelT]:
        """Return the canonical executor for the currently bound runtime."""

    async def dispose(self) -> None:
        if self._disposed:
            return
        try:
            await self.on_dispose()
        finally:
            self._disposed = True
            self._executor = None
            self._binding = None

    async def on_dispose(self) -> None:
        """Optional hook for resource cleanup."""
