# -----------------------------------------------------------------------------
# BUILD STAGE
# -----------------------------------------------------------------------------
FROM mirror.gcr.io/python:3.12.8-slim AS builder

ARG USER_NAME=fred-user
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN apt-get update && \
    apt-get install -y curl make && \
    rm -rf /var/lib/apt/lists/*

RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    mv /root/.local/bin/uv /usr/local/bin/uv && \
    chmod +x /usr/local/bin/uv

ENV UV_PROJECT_ENVIRONMENT=/app/venv
ENV PATH="/app/venv/bin:$PATH"

WORKDIR /app

COPY control-plane-backend/pyproject.toml /app/
COPY control-plane-backend/Makefile /app/
COPY scripts /scripts
COPY fred-core /fred-core

RUN make dev

COPY control-plane-backend/. /app/

# -----------------------------------------------------------------------------
# FINAL STAGE
# -----------------------------------------------------------------------------
FROM mirror.gcr.io/python:3.12.8-slim

ARG USER_NAME=fred-user
ARG USER_ID=1000
ARG GROUP_ID=1000
ARG PRODUCTION_FASTAPI_DOCS_ENABLED=false

RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

RUN groupadd -g ${GROUP_ID} ${USER_NAME} && \
    useradd -u ${USER_ID} -g ${GROUP_ID} -m ${USER_NAME}

COPY --from=builder --chown=${USER_ID}:${GROUP_ID} /app/venv /app/venv
ENV PATH="/app/venv/bin:$PATH"
ENV PRODUCTION_FASTAPI_DOCS_ENABLED=${PRODUCTION_FASTAPI_DOCS_ENABLED}

WORKDIR /app

COPY --chown=${USER_ID}:${GROUP_ID} control-plane-backend/. /app
COPY --chown=${USER_ID}:${GROUP_ID} fred-core /fred-core
COPY --chown=${USER_ID}:${GROUP_ID} scripts /scripts

ENV PYTHONPATH=/app

USER ${USER_NAME}

EXPOSE 8222

ENTRYPOINT ["uvicorn", "control_plane_backend.main:create_app", "--factory"]
CMD ["--port", "8222", "--host", "0.0.0.0", "--log-level", "info", "--loop", "asyncio"]
